apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-js-app
  template:
    metadata:
      labels:
        app: node-js-app
    spec:
      containers:
      - name: node-js-app
        image: salma9345801442/node_js01:latest
        ports:
        - containerPort: 3000
