name: Build, Push and Deploy Node.js App
 
on: 
  push:
    branches: [ main ] 
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: salma9345801442/node_js01:latest

    - name: Deploy to Minikube on EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull salma9345801442/node_js01:latest
          kubectl apply -f ~/node_js01/k8s/deployment.yaml
          kubectl apply -f ~/node_js01/k8s/service.yml
          kubectl get pods
          kubectl get svc
